export default {
  "login": "LucasCardoso20",
  "id": 81536211,
  "node_id": "MDQ6VXNlcjgxNTM2MjEx",
  "avatar_url": "https://avatars.githubusercontent.com/u/81536211?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/LucasCardoso20",
  "html_url": "https://github.com/LucasCardoso20",
  "followers_url": "https://api.github.com/users/LucasCardoso20/followers",
  "following_url": "https://api.github.com/users/LucasCardoso20/following{/other_user}",
  "gists_url": "https://api.github.com/users/LucasCardoso20/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/LucasCardoso20/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/LucasCardoso20/subscriptions",
  "organizations_url": "https://api.github.com/users/LucasCardoso20/orgs",
  "repos_url": "https://api.github.com/users/LucasCardoso20/repos",
  "events_url": "https://api.github.com/users/LucasCardoso20/events{/privacy}",
  "received_events_url": "https://api.github.com/users/LucasCardoso20/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Lucas Cardoso",
  "company": null,
  "blog": "lucascardoso.netlify.app",
  "location": "Rio De Janeiro",
  "email": null,
  "hireable": null,
  "bio": "A guy from Rio de Janeiro, Brazil, who loves sports, coding and idioms. ",
  "twitter_username": null,
  "public_repos": 23,
  "public_gists": 0,
  "followers": 0,
  "following": 3,
  "created_at": "2021-03-28T21:46:57Z",
  "updated_at": "2022-06-03T12:13:47Z"
};
